In [9]:
import numpy as np
import pandas as pd

data=pd.read_csv(r"C:\Users\MSI GF63\Documents\UiTM Stuff\Semester 4\ISP560 - Machine Learning\Group Project\Income.csv")
print(data)


       age  workclass  educational-num         occupation  hours-per-week  \
0       67    Private               16    Exec-managerial              60   
1       17    Private                8      Other-service              15   
2       31    Private               13    Exec-managerial              40   
3       58  State-gov                4   Transport-moving              40   
4       25  State-gov               10      Other-service              40   
...    ...        ...              ...                ...             ...   
43952   52    Private               13    Exec-managerial              50   
43953   19    Private                9      Other-service              40   
43954   30    Private               10              Sales              58   
43955   46    Private               13              Sales              35   
43956   30    Private                9  Handlers-cleaners              40   

       income_>50K  
0                1  
1                0  
2           

In [10]:
from sklearn.preprocessing import LabelEncoder

data=pd.DataFrame(data,columns=['age','workclass','educational-num','occupation','hours-per-week','income_>50K'])
x=data.iloc[:,0:6].values
y=data.iloc[:,-1].values

le = LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
x[:,3]=le.fit_transform(x[:,3])
print(x)

[[67 4 16 4 60 1]
 [17 4 8 8 15 0]
 [31 4 13 4 40 1]
 ...
 [30 4 10 12 58 0]
 [46 4 13 12 35 0]
 [30 4 9 6 40 0]]


In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.6, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
print(x_train)
print('****************************************************************************')
print(x_test)

[[-1.14097909  0.0862267  -0.41132665  0.33013318 -0.45012031 -0.56399451]
 [ 0.68372896  0.0862267  -0.41132665  0.33013318 -0.04264766 -0.56399451]
 [-0.70304916 -1.97922     0.74757701 -1.33451819 -0.04264766 -0.56399451]
 ...
 [ 0.82970561  2.1516734  -0.41132665 -1.33451819 -0.04264766 -0.56399451]
 [ 0.02683406  0.0862267  -0.02502543 -1.33451819  0.77229764  1.77306689]
 [-0.33810755  0.0862267   1.52017945 -0.62109618 -0.04264766 -0.56399451]]
****************************************************************************
[[ 1.26434944 -1.27597257  1.52757011  0.80944142 -0.02648089 -0.55873881]
 [-0.33489798  0.09067825 -0.0313106   1.28097198  1.17495295  1.78974502]
 [ 0.97357718  0.09067825  1.52757011  0.80944142 -0.02648089  1.78974502]
 ...
 [ 0.3193396   0.09067825  0.74812976 -0.84091553 -0.02648089 -0.55873881]
 [-1.27990782  0.09067825 -2.36963167 -0.36938497 -0.18667207 -0.55873881]
 [-0.9164425   0.09067825  0.35840958 -1.31244609 -0.02648089 -0.55873881]]


In [33]:
#Backpropagation process
import tensorflow as tf
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=5, activation = 'relu')) #For 5 input nodes
model.add(tf.keras.layers.Dense(units=10, activation = 'relu')) #For 10 hidden nodes
model.add(tf.keras.layers.Dense(units=2, activation = 'sigmoid')) #For 2 output nodes
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=6, batch_size=128)


Epoch 1/6
138/138 [==============================] - 0s 889us/step - loss: 0.6780 - accuracy: 0.6606
Epoch 2/6
138/138 [==============================] - 0s 851us/step - loss: 0.2427 - accuracy: 0.9744
Epoch 3/6
138/138 [==============================] - 0s 721us/step - loss: 0.0633 - accuracy: 0.9977
Epoch 4/6
138/138 [==============================] - 0s 713us/step - loss: 0.0214 - accuracy: 0.9998
Epoch 5/6
138/138 [==============================] - 0s 801us/step - loss: 0.0096 - accuracy: 0.9999
Epoch 6/6
138/138 [==============================] - 0s 764us/step - loss: 0.0052 - accuracy: 0.9999


In [18]:
y_pred = model.predict(x_test)
print(y_pred)

for i in range(len(y_pred)):
    print(np.argmax(y_pred[i]))

138/138 [==============================] - 0s 728us/step
[[9.9997842e-01 2.4535836e-07]
 [1.4217602e-06 9.9999559e-01]
 [7.4347435e-07 9.9999762e-01]
 ...
 [9.9998850e-01 9.7520804e-08]
 [9.9996746e-01 1.7014634e-07]
 [1.1501124e-06 9.9999642e-01]]
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
1
0
0
1
0
1
0
1
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
1
0
1
0
0
0
0
0
0
1
0
0
0
0
0
1
0
1
0
0
0
1
1
1
0
0
0
1
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
1
0
1
0
0
1
0
0
0
1
1
0
0
1
0
1
0
0
1
1
0
0
0
0
0
1
1
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
1
1
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
1
0
0
1
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0